### ISSUE TITLE
T-Beam v1.2 supported or not?

### ISSUE THREAD

**Issue by Pilotkosinus** [tb0hdan/meshtastic-telegram-gateway#222]
I ordered the [Aliexpress NEO-8M (better) from the readme file. But in the list of supported devices I only see T-Beam v1.1.

On Aliexpress it says v1.2. is this also supported or not?

**Comment by tb0hdan** [comment]
Yes, it is: https://github.com/meshtastic/python/blob/master/meshtastic/supported_device.py#L58
