### ISSUE TITLE
How to "Proposed hybrid architecture, used by community in Ukraine"

### ISSUE THREAD

**Issue by nicopace** [tb0hdan/meshtastic-telegram-gateway#385]
I am interested in bridging a meshtastic network with Baofengs... but just starting on the research.
Any pointer would be highly appreciated!

**Comment by tb0hdan** [comment]
Baofengs are just FM radios, they do no support LoRa. You'll need to purchase something that runs Meshtastic firmware. 
See https://meshtastic.org/docs/hardware/devices/

**Comment by nicopace** [comment]
thanks for replying.
I understand that they will not work in the same frequency.
I was wondering how did you implemented it?
I imagined using baofengs with TRS and a modem to send mqtt messages over, or something like that.
But would love to know how it is done over there.
Thanks!

**Comment by tb0hdan** [comment]
Unfortunately, LoRa (radio protocol used by Meshtastic) is proprietary, and therefore not compatible with any of the FM devices (including Baofeng). Ukrainian network is build using a mix of different devices, but it all started with T-Beam-s: https://www.aliexpress.com/item/1005003088139358.html

**Comment by nicopace** [comment]
Thanks for your response.
I am interested in creating similar networks for wildfire response.
Baofeng radios (with their repeaters already deployed) would act as repeaters for the meshtastic networks.
This would be accomplished by having meshtastic nodes connected to an MQTT broker, and a node connected to the broker that would repeat the signal over the baofeng network.
I would have thought that you might have done something of the sort, and was interested in hearing about the experience, whether this was a good approach or would be best to go in another direction.
This would allow for a meshtastic network to work across a wider distance, interconnecting different clusters of nodes.

**Comment by tb0hdan** [comment]
As I've said before, Baofengs don't do LoRa (Meshtastic). But, what you actually can do, given that Meshtastic messages are really short, is to have an audio cable connected to Baofeng and then sent over using AFSK1200. Your setup would look like this:

Meshtastic -> Meshtastic -> Raspberry Pi -> Audio -> Baofeng -> Baofeng -> Audio -> Raspberry Pi -> Meshtastic -> Meshtastic
